//
// Created by gregorian-rayne on 12/28/25.
//

#ifndef BHA_CLANG_PARSER_HPP
#define BHA_CLANG_PARSER_HPP

/**
 * @file clang_parser.hpp
 * @brief Clang -ftime-trace JSON parser.
 *
 * Parses the JSON output generated by Clang's -ftime-trace flag.
 * The format is a Chrome Trace Event format JSON file containing
 * timing information for compilation phases.
 */

#include "bha/parsers/parser.hpp"

namespace bha::parsers {

    /**
     * Parser for Clang's -ftime-trace JSON output.
     *
     * Clang's -ftime-trace generates a JSON file in Chrome Trace Event format.
     * This parser extracts:
     * - Frontend/backend timing
     * - Template instantiation times
     * - Header inclusion times
     * - Code generation times
     */
    class ClangTraceParser : public ITraceParser {
    public:
        /// Human-readable parser name.
        [[nodiscard]] std::string_view name() const noexcept override {
            return "Clang";
        }

        /// Compiler family handled by this parser.
        [[nodiscard]] CompilerType compiler_type() const noexcept override {
            return CompilerType::Clang;
        }

        /// Preferred trace artifact extension for clang `-ftime-trace`.
        [[nodiscard]] std::vector<std::string> supported_extensions() const override {
            return {".json"};
        }

        /// Quick path-based eligibility check.
        [[nodiscard]] bool can_parse(const fs::path& path) const override;

        /// Content-signature check for Chrome Trace Event JSON.
        [[nodiscard]] bool can_parse_content(std::string_view content) const override;

        /// Parse a clang time-trace file into one normalized compilation unit.
        [[nodiscard]] Result<CompilationUnit, Error> parse_file(
            const fs::path& path
        ) const override;

        /// Parse in-memory clang time-trace content with optional source hint.
        [[nodiscard]] Result<CompilationUnit, Error> parse_content(
            std::string_view content,
            const fs::path& source_hint
        ) const override;
    };

    /**
     * Registers the Clang parser with the global registry.
     *
     * Call this during initialization to enable Clang trace parsing.
     */
    void register_clang_parser();

}  // namespace bha::parsers

#endif //BHA_CLANG_PARSER_HPP
