//
// Created by gregorian-rayne on 12/28/25.
//

#ifndef BUILDTIMEHOTSPOTANALYZER_GCC_PARSER_HPP
#define BUILDTIMEHOTSPOTANALYZER_GCC_PARSER_HPP

/**
 * @file gcc_parser.hpp
 * @brief GCC -ftime-report parser.
 *
 * Parses the text output generated by GCC's -ftime-report flag.
 * The format is a human-readable text report showing time spent
 * in various compilation phases.
 */

#include "bha/parsers/parser.hpp"

namespace bha::parsers {

    /**
     * Parser for GCC's -ftime-report text output.
     *
     * GCC's -ftime-report generates a text report with timing information
     * for compilation phases. This parser extracts:
     * - Phase timing (parsing, preprocessing, code generation, etc.)
     * - Template instantiation summaries
     * - Memory usage statistics
     *
     * Example output format:
     *   Time variable                                   usr           sys          wall
     *   phase parsing                         :   0.12 (  8%)   0.01 (  5%)   0.13 (  8%)
     *   phase lang. deferred                  :   0.02 (  1%)   0.00 (  0%)   0.02 (  1%)
     *   ...
     */
    class GCCTraceParser : public ITraceParser {
    public:
        [[nodiscard]] std::string_view name() const noexcept override {
            return "GCC";
        }

        [[nodiscard]] CompilerType compiler_type() const noexcept override {
            return CompilerType::GCC;
        }

        [[nodiscard]] std::vector<std::string> supported_extensions() const override {
            return {".txt", ".log", ".report"};
        }

        [[nodiscard]] bool can_parse(const fs::path& path) const override;

        [[nodiscard]] bool can_parse_content(std::string_view content) const override;

        [[nodiscard]] Result<CompilationUnit, Error> parse_file(
            const fs::path& path
        ) const override;

        [[nodiscard]] Result<CompilationUnit, Error> parse_content(
            std::string_view content,
            const fs::path& source_hint
        ) const override;
    };

    /**
     * Registers the GCC parser with the global registry.
     */
    void register_gcc_parser();

}  // namespace bha::parsers

#endif //BUILDTIMEHOTSPOTANALYZER_GCC_PARSER_HPP