//
// Created by gregorian-rayne on 12/28/25.
//

#ifndef BHA_MSVC_PARSER_HPP
#define BHA_MSVC_PARSER_HPP

/**
 * @file msvc_parser.hpp
 * @brief MSVC /Bt+ and /d1reportTime parser.
 *
 * Parses the timing output generated by MSVC's /Bt+ flag (build timing)
 * and /d1reportTime (detailed front-end timing).
 */

#include "bha/parsers/parser.hpp"

namespace bha::parsers {

    /**
     * Parser for MSVC timing output.
     *
     * MSVC provides timing information through:
     * - /Bt+ : Shows c1xx.dll and c2.dll timing (front-end and back-end)
     * - /d1reportTime : Detailed front-end timing breakdown
     *
     * Example /Bt+ output:
     *   time(C:\path\file.cpp)=0.852s
     *   time(c1xx.dll)=0.612s < 0.589s (Frontend), 0.023s (Template instantiation) >
     *   time(c2.dll)=0.240s
     */
    class MSVCTraceParser : public ITraceParser {
    public:
        /// Human-readable parser name.
        [[nodiscard]] std::string_view name() const noexcept override {
            return "MSVC";
        }

        /// Compiler family handled by this parser.
        [[nodiscard]] CompilerType compiler_type() const noexcept override {
            return CompilerType::MSVC;
        }

        /// Common text/log extensions used to capture MSVC timing output.
        [[nodiscard]] std::vector<std::string> supported_extensions() const override {
            return {".txt", ".log", ".btlog"};
        }

        /// Quick path-based eligibility check.
        [[nodiscard]] bool can_parse(const fs::path& path) const override;

        /// Content-signature check for `/Bt+` and `/d1reportTime` output.
        [[nodiscard]] bool can_parse_content(std::string_view content) const override;

        /// Parse an MSVC timing trace file into one compilation unit.
        [[nodiscard]] Result<CompilationUnit, Error> parse_file(
            const fs::path& path
        ) const override;

        /// Parse in-memory MSVC timing content with optional source hint.
        [[nodiscard]] Result<CompilationUnit, Error> parse_content(
            std::string_view content,
            const fs::path& source_hint
        ) const override;
    };

    /**
     * Registers the MSVC parser with the global registry.
     */
    void register_msvc_parser();

}  // namespace bha::parsers

#endif //BHA_MSVC_PARSER_HPP
