#!/usr/bin/env python3
"""
Generate C++ resource headers from binary files.
Embeds resources as constexpr byte arrays to avoid MSVC C2026 errors.
"""

import sys
import os

def generate_resource_header(input_file, var_name, output_file):
    """
    Generate a C++ header with embedded resource data.

    Args:
        input_file: Path to input resource file
        var_name: C++ variable name for the resource
        output_file: Path to output header file
    """
    with open(input_file, 'rb') as f:
        data = f.read()

    file_size = len(data)
    filename = os.path.basename(input_file)
    rel_path = os.path.relpath(input_file, os.path.dirname(output_file) + '/../')

    # Generate byte array content with proper formatting
    # Format: 16 bytes per line for readability
    byte_lines = []
    for i in range(0, file_size, 16):
        chunk = data[i:i+16]
        byte_str = ', '.join(f'0x{b:02x}' for b in chunk)
        byte_lines.append(f'    {byte_str}')

    array_content = ',\n'.join(byte_lines)

    # Generate header content
    header_content = f'''// Auto-generated resource file: {filename}
// Generated from: {rel_path}
// Size: {file_size} bytes
// DO NOT EDIT - This file is automatically generated

#pragma once

#include <string_view>

namespace bha {{
namespace resources {{

// Embedded resource data as byte array for {filename}
// Using byte array to avoid MSVC C2026 (16KB string literal limit)
inline constexpr unsigned char {var_name}_BYTES[] = {{
{array_content}
}};

// Provide as string_view (inline, not constexpr due to reinterpret_cast)
inline const std::string_view {var_name}(
    reinterpret_cast<const char*>({var_name}_BYTES),
    sizeof({var_name}_BYTES)
);

}} // namespace resources
}} // namespace bha
'''

    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"Generated {output_file} ({file_size} bytes)")

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print("Usage: generate_resource_header.py <input_file> <var_name> <output_file>")
        sys.exit(1)

    generate_resource_header(sys.argv[1], sys.argv[2], sys.argv[3])
