//
// Created by gregorian-rayne on 12/30/25.
//

#include "bha/exporters/exporter.hpp"

#include <nlohmann/json.hpp>

// Embedded resource headers (generated by CMake from resources/)
#include "d3_js.hpp"
#include "fontawesome_css.hpp"
#include "report_head.hpp"
#include "report_body_start.hpp"
#include "report_body_sections.hpp"
#include "report_body_end.hpp"
#include "styles_css.hpp"
#include "visualization_js.hpp"

#include <algorithm>
#include <chrono>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <map>
#include <numeric>
#include <sstream>
#include <unordered_set>

namespace bha::exporters
{
    namespace {

        /**
         * Formats a timestamp to ISO 8601.
         */
        std::string format_timestamp(const Timestamp ts) {
            const auto time_t_val = std::chrono::system_clock::to_time_t(ts);
            std::ostringstream ss;

#ifdef _WIN32
            std::tm time_info{};
            gmtime_s(&time_info, &time_t_val);
            ss << std::put_time(&time_info, "%Y-%m-%dT%H:%M:%SZ");
#else
            ss << std::put_time(std::gmtime(&time_t_val), "%Y-%m-%dT%H:%M:%SZ");
#endif

            return ss.str();
        }

        /**
         * Formats a duration to milliseconds.
         */
        double duration_to_ms(const Duration d) {
            return static_cast<double>(std::chrono::duration_cast<std::chrono::microseconds>(d).count()) / 1000.0;
        }

        std::string format_duration_human(const Duration d) {
            const double ms = duration_to_ms(d);
            std::ostringstream ss;
            if (ms >= 1000.0) {
                ss << std::fixed << std::setprecision(3) << (ms / 1000.0) << " s";
            } else {
                ss << std::fixed << std::setprecision(2) << ms << " ms";
            }
            return ss.str();
        }

        /**
         * Normalizes path separators to forward slashes for consistent graph IDs.
         * Uses generic_string() for fs::path which is cross-platform portable.
         * For string input, manually converts backslashes (for paths from external sources).
         */
        std::string normalize_path(const fs::path& path) {
            return path.generic_string();
        }

        std::string normalize_path(const std::string& path) {
            // For string paths (e.g., from included_by), convert to fs::path first
            // to leverage generic_string() for cross-platform normalization
            return fs::path(path).generic_string();
        }

        /**
         * Escapes HTML special characters.
         */
        std::string escape_html(const std::string& text) {
            std::string result;
            result.reserve(static_cast<std::size_t>(static_cast<double>(text.size()) * 1.1));
            for (const char c : text) {
                switch (c) {
                case '&': result += "&amp;"; break;
                case '<': result += "&lt;"; break;
                case '>': result += "&gt;"; break;
                case '"': result += "&quot;"; break;
                case '\'': result += "&#39;"; break;
                default: result += c; break;
                }
            }
            return result;
        }

        std::string format_markdown_simple(const std::string& markdown) {
            std::string html;
            std::istringstream stream(markdown);
            std::string line;
            bool in_list = false;
            bool in_code_block = false;
            std::string code_block_content;

            while (std::getline(stream, line)) {
                if (line.find("```") == 0) {
                    if (in_code_block) {
                        html += R"(<pre class="code-block" style="margin: 6px 0; padding: 12px; background: var(--bg-secondary); border-radius: 6px; border-left: 3px solid var(--accent-color); overflow-x: auto;">)";
                        html += escape_html(code_block_content);
                        html += "</pre>\n";
                        code_block_content.clear();
                        in_code_block = false;
                    } else {
                        if (in_list) {
                            html += "</ul>\n";
                            in_list = false;
                        }
                        in_code_block = true;
                    }
                    continue;
                }

                if (in_code_block) {
                    code_block_content += line + "\n";
                    continue;
                }

                if (line.empty()) {
                    if (in_list) {
                        html += "</ul>\n";
                        in_list = false;
                    }
                    continue;
                }

                if (line.find("  - ") == 0 || line.find("- ") == 0) {
                    if (!in_list) {
                        html += "<ul style=\"margin: 8px 0; padding-left: 24px;\">\n";
                        in_list = true;
                    }
                    std::string item = line.substr(line.find("- ") + 2);
                    html += "<li>" + escape_html(item) + "</li>\n";
                    continue;
                }

                if (in_list) {
                    html += "</ul>\n";
                    in_list = false;
                }

                std::string processed = line;
                size_t pos = 0;
                while ((pos = processed.find("**", pos)) != std::string::npos) {
                    if (size_t end_pos = processed.find("**", pos + 2); end_pos != std::string::npos) {
                        std::string bold_text = processed.substr(pos + 2, end_pos - pos - 2);
                        std::string replacement = "<strong>" + bold_text + "</strong>";
                        processed.replace(pos, end_pos - pos + 2, replacement);
                        pos += replacement.length();
                    } else {
                        break;
                    }
                }

                html += "<p style=\"margin: 2px 0;\">" + processed + "</p>\n";
            }

            if (in_list) {
                html += "</ul>\n";
            }

            if (in_code_block && !code_block_content.empty()) {
                html += R"(<pre class="code-block" style="margin: 6px 0; padding: 12px; background: var(--bg-secondary); border-radius: 6px; border-left: 3px solid var(--accent-color); overflow-x: auto;">)";
                html += escape_html(code_block_content);
                html += "</pre>\n";
            }

            return html;
        }

        std::size_t count_lines(const std::string& text) {
            if (text.empty()) return 0;
            return static_cast<std::size_t>(std::count(text.begin(), text.end(), '\n')) + 1;
        }

        std::string truncate_lines(const std::string& text, const std::size_t max_lines) {
            if (max_lines == 0 || text.empty()) return {};
            std::size_t line_count = 0;
            std::size_t pos = 0;
            for (; pos < text.size(); ++pos) {
                if (text[pos] == '\n') {
                    ++line_count;
                    if (line_count >= max_lines) {
                        ++pos;
                        break;
                    }
                }
            }
            return text.substr(0, pos);
        }

        /**
         * Replaces multiple placeholders in a template string.
         */
        std::string replace_placeholders(const std::string_view tmpl,
                                        const std::vector<std::pair<std::string, std::string>>& replacements) {
            std::string result(tmpl);
            for (const auto& [placeholder, value] : replacements) {
                size_t pos = 0;
                while ((pos = result.find(placeholder, pos)) != std::string::npos) {
                    result.replace(pos, placeholder.length(), value);
                    pos += value.length();
                }
            }
            return result;
        }

        /**
         * Escapes CSV special characters.
         */
        std::string escape_csv(const std::string& text) {
            if (text.find_first_of(",\"\n\r") == std::string::npos) {
                return text;
            }
            std::string result = "\"";
            for (const char c : text) {
                if (c == '"') {
                    result += "\"\"";
                } else {
                    result += c;
                }
            }
            result += "\"";
            return result;
        }

        std::string application_mode_label(const Suggestion& suggestion) {
            if (suggestion.application_summary && !suggestion.application_summary->empty()) {
                return *suggestion.application_summary;
            }
            switch (resolve_application_mode(suggestion)) {
                case SuggestionApplicationMode::DirectEdits:
                    return "Direct Edits";
                case SuggestionApplicationMode::ExternalRefactor:
                    return "Refactor Tool";
                case SuggestionApplicationMode::Advisory:
                    return "Manual Review";
            }
            return "Manual Review";
        }

        std::string application_mode_note(const Suggestion& suggestion) {
            if (suggestion.application_guidance && !suggestion.application_guidance->empty()) {
                return *suggestion.application_guidance;
            }
            switch (resolve_application_mode(suggestion)) {
                case SuggestionApplicationMode::DirectEdits:
                    return "BHA can apply this suggestion with direct text edits, rebuild-validate the change, and roll back from backup if validation fails.";
                case SuggestionApplicationMode::ExternalRefactor:
                    return "BHA applies this through the semantic refactor tool, rebuild-validates the result, and rolls back from backup if validation fails.";
                case SuggestionApplicationMode::Advisory:
                    return "This suggestion is intentionally advisory. Review and apply it manually.";
            }
            return "This suggestion is intentionally advisory. Review and apply it manually.";
        }

    }  // namespace

    // =============================================================================
    // Format Conversion
    // =============================================================================

    std::string_view format_to_string(const ExportFormat format) noexcept {
        switch (format) {
        case ExportFormat::JSON: return "json";
        case ExportFormat::HTML: return "html";
        case ExportFormat::CSV: return "csv";
        case ExportFormat::SARIF: return "sarif";
        case ExportFormat::Markdown: return "markdown";
        }
        return "unknown";
    }

    std::optional<ExportFormat> string_to_format(const std::string_view str) noexcept {
        if (str == "json" || str == "JSON") return ExportFormat::JSON;
        if (str == "html" || str == "HTML") return ExportFormat::HTML;
        if (str == "csv" || str == "CSV") return ExportFormat::CSV;
        if (str == "sarif" || str == "SARIF") return ExportFormat::SARIF;
        if (str == "markdown" || str == "md" || str == "Markdown") return ExportFormat::Markdown;
        return std::nullopt;
    }

    // =============================================================================
    // Exporter Factory
    // =============================================================================

    Result<std::unique_ptr<IExporter>, Error> ExporterFactory::create(const ExportFormat format) {
        switch (format) {
        case ExportFormat::JSON:
            return Result<std::unique_ptr<IExporter>, Error>::success(
                std::make_unique<JsonExporter>()
            );
        case ExportFormat::HTML:
            return Result<std::unique_ptr<IExporter>, Error>::success(
                std::make_unique<HtmlExporter>()
            );
        case ExportFormat::CSV:
            return Result<std::unique_ptr<IExporter>, Error>::success(
                std::make_unique<CsvExporter>()
            );
        case ExportFormat::Markdown:
            return Result<std::unique_ptr<IExporter>, Error>::success(
                std::make_unique<MarkdownExporter>()
            );
        case ExportFormat::SARIF:
            return Result<std::unique_ptr<IExporter>, Error>::failure(
                Error(ErrorCode::NotFound, "SARIF exporter not yet implemented")
            );
        }
        return Result<std::unique_ptr<IExporter>, Error>::failure(
            Error(ErrorCode::InvalidArgument, "Unknown export format")
        );
    }

    Result<std::unique_ptr<IExporter>, Error> ExporterFactory::create_for_file(const fs::path& path) {
        std::string ext = path.extension().string();
        std::ranges::transform(ext, ext.begin(),
                               [](const unsigned char c) { return static_cast<char>(std::tolower(c)); });

        if (ext == ".json") return create(ExportFormat::JSON);
        if (ext == ".html" || ext == ".htm") return create(ExportFormat::HTML);
        if (ext == ".csv") return create(ExportFormat::CSV);
        if (ext == ".md" || ext == ".markdown") return create(ExportFormat::Markdown);
        if (ext == ".sarif") return create(ExportFormat::SARIF);

        return Result<std::unique_ptr<IExporter>, Error>::failure(
            Error(ErrorCode::InvalidArgument, "Cannot determine format from extension: " + ext)
        );
    }

    std::vector<ExportFormat> ExporterFactory::available_formats() {
        return {
            ExportFormat::JSON,
            ExportFormat::HTML,
            ExportFormat::CSV,
            ExportFormat::Markdown
        };
    }

    // =============================================================================
    // JSON Exporter
    // =============================================================================

    Result<void, Error> JsonExporter::export_to_file(
        const fs::path& path,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        const ExportProgressCallback progress
    ) const {
        std::ofstream file(path);
        if (!file.is_open()) {
            return Result<void, Error>::failure(
                Error(ErrorCode::IoError, "Failed to open file for writing: " + path.string())
            );
        }
        return export_to_stream(file, analysis, suggestions, options, progress);
    }

    Result<void, Error> JsonExporter::export_to_stream(
        std::ostream& stream,
        const analyzers::AnalysisResult& analysis,
        [[maybe_unused]] const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        ExportProgressCallback progress
    ) const {
        using json = nlohmann::json;

        json output;

        // Metadata
        if (options.include_metadata) {
            output["$schema"] = "https://bha.dev/schemas/analysis-v" + options.json_schema_version + ".json";
            output["schema_version"] = options.json_schema_version;
            output["bha_version"] = "1.0.0";
            output["generated_at"] = format_timestamp(std::chrono::system_clock::now());
        }

        json summary;
        summary["total_files"] = analysis.files.size();
        summary["total_compile_time_ms"] = duration_to_ms(analysis.performance.total_build_time);
        summary["analysis_duration_ms"] = duration_to_ms(analysis.analysis_duration);
        summary["cache_hit_opportunity_percent"] = analysis.cache_distribution.cache_hit_opportunity_percent;
        summary["cache_risk_compilations"] = analysis.cache_distribution.cache_risk_compilations;
        summary["distributed_suitability_score"] = analysis.cache_distribution.distributed_suitability_score;

        if (analysis.performance.total_memory.has_data()) {
            json memory_summary;
            memory_summary["max_stack_bytes"] = analysis.performance.peak_memory.max_stack_bytes;
            summary["memory"] = memory_summary;
        }

        output["summary"] = summary;

        if (options.include_file_details) {
            json files = json::array();
            std::size_t file_count = 0;
            std::size_t total_files = analysis.files.size();

            for (const auto& file : analysis.files) {
                if (options.min_compile_time > Duration::zero() &&
                    file.compile_time < options.min_compile_time) {
                    continue;
                    }

                if (options.max_files > 0 && file_count >= options.max_files) {
                    break;
                }

                json file_entry;
                file_entry["path"] = file.file.string();
                file_entry["total_time_ms"] = duration_to_ms(file.compile_time);
                file_entry["frontend_time_ms"] = duration_to_ms(file.frontend_time);
                file_entry["backend_time_ms"] = duration_to_ms(file.backend_time);
                file_entry["include_count"] = file.include_count;

                if (file.memory.has_data()) {
                    json memory;
                    memory["max_stack_bytes"] = file.memory.max_stack_bytes;
                    file_entry["memory"] = memory;
                }

                files.push_back(file_entry);
                file_count++;

                if (progress) {
                    progress(file_count, total_files, "Exporting files");
                }
            }
            output["files"] = files;
        }

        if (options.include_dependencies && !analysis.dependencies.headers.empty()) {
            json deps;
            deps["total_includes"] = analysis.dependencies.total_includes;
            deps["unique_headers"] = analysis.dependencies.unique_headers;
            deps["max_depth"] = analysis.dependencies.max_include_depth;
            deps["circular_dependencies_count"] = analysis.dependencies.circular_dependencies.size();

            json headers_array = json::array();
            for (const auto& header : analysis.dependencies.headers) {
                json h;
                h["path"] = header.path.string();
                h["inclusion_count"] = header.inclusion_count;
                h["including_files"] = header.including_files;
                h["parse_time_ms"] = duration_to_ms(header.total_parse_time);
                h["impact_score"] = header.impact_score;
                h["included_by"] = header.included_by;
                h["modification_count"] = header.modification_count;
                h["is_stable"] = header.is_stable;
                h["is_external"] = header.is_external;
                headers_array.push_back(h);
            }
            deps["headers"] = headers_array;

            json nodes = json::array();
            json links = json::array();
            std::unordered_set<std::string> seen;

            for (const auto& file : analysis.files) {
                if (std::string file_id = normalize_path(file.file.string()); seen.insert(file_id).second) {
                    nodes.push_back({
                        {"id", file_id},
                        {"type", "source"}
                    });
                }
            }

            for (const auto& hinfo : analysis.dependencies.headers) {
                if (std::string hdr_id = normalize_path(hinfo.path.string()); seen.insert(hdr_id).second) {
                    nodes.push_back({
                        {"id", hdr_id},
                        {"type", "header"}
                    });
                }
            }

            for (const auto& hinfo : analysis.dependencies.headers) {
                std::string hdr_id = normalize_path(hinfo.path.string());
                for (const auto& incl_by : hinfo.included_by) {
                    links.push_back({
                        {"source", normalize_path(incl_by)},
                        {"target", hdr_id},
                        {"type", "include"}
                    });
                }
            }

            deps["graph"] = {
                {"nodes", nodes},
                {"links", links}
            };

            output["dependencies"] = deps;
        }

        if (options.include_templates && !analysis.templates.templates.empty()) {
            json templates;
            templates["total_instantiations"] = analysis.templates.total_instantiations;
            templates["total_time_ms"] = duration_to_ms(analysis.templates.total_template_time);

            json tmpl_array = json::array();
            for (const auto& tmpl : analysis.templates.templates) {
                json t;
                t["name"] = !tmpl.full_signature.empty() ? tmpl.full_signature : tmpl.name;
                t["type"] = tmpl.name;  // Keep original event type (InstantiateClass, etc.)
                t["count"] = tmpl.instantiation_count;
                t["time_ms"] = duration_to_ms(tmpl.total_time);
                t["time_percent"] = tmpl.time_percent;
                tmpl_array.push_back(t);
            }
            templates["templates"] = tmpl_array;

            output["templates"] = templates;
        }

        const auto& cache = analysis.cache_distribution;
        if (cache.total_compilations > 0) {
            json cache_json;
            cache_json["total_compilations"] = cache.total_compilations;
            cache_json["cache_friendly_compilations"] = cache.cache_friendly_compilations;
            cache_json["cache_risk_compilations"] = cache.cache_risk_compilations;
            cache_json["cache_hit_opportunity_percent"] = cache.cache_hit_opportunity_percent;
            cache_json["sccache_detected"] = cache.sccache_detected;
            cache_json["fastbuild_detected"] = cache.fastbuild_detected;
            cache_json["cache_wrapper_detected"] = cache.cache_wrapper_detected;
            cache_json["dynamic_macro_risk_count"] = cache.dynamic_macro_risk_count;
            cache_json["profile_or_coverage_risk_count"] = cache.profile_or_coverage_risk_count;
            cache_json["pch_generation_risk_count"] = cache.pch_generation_risk_count;
            cache_json["volatile_path_risk_count"] = cache.volatile_path_risk_count;
            cache_json["heavy_translation_units"] = cache.heavy_translation_units;
            cache_json["homogeneous_command_units"] = cache.homogeneous_command_units;
            cache_json["distributed_suitability_score"] = cache.distributed_suitability_score;
            output["cache_distribution"] = cache_json;
        }

        if (options.include_symbols && !analysis.symbols.symbols.empty()) {
            json symbols;
            symbols["total_symbols"] = analysis.symbols.total_symbols;
            symbols["unused_symbols"] = analysis.symbols.unused_symbols;

            json sym_array = json::array();
            for (const auto& sym : analysis.symbols.symbols) {
                json s;
                s["name"] = sym.name;
                s["type"] = sym.type;
                s["defined_in"] = sym.defined_in.string();
                s["usage_count"] = sym.usage_count;
                sym_array.push_back(s);
            }
            symbols["symbols"] = sym_array;

            output["symbols"] = symbols;
        }

        if (options.pretty_print) {
            stream << std::setw(2) << output << std::endl;
        } else {
            stream << output << std::endl;
        }

        return Result<void, Error>::success();
    }

    Result<std::string, Error> JsonExporter::export_to_string(
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options
    ) const {
        std::ostringstream ss;
        if (auto result = export_to_stream(ss, analysis, suggestions, options, nullptr); result.is_err()) {
            return Result<std::string, Error>::failure(result.error());
        }
        return Result<std::string, Error>::success(ss.str());
    }

    // =============================================================================
    // HTML Exporter
    // =============================================================================

    Result<void, Error> HtmlExporter::export_to_file(
        const fs::path& path,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        const ExportProgressCallback progress
    ) const {
        std::ofstream file(path);
        if (!file.is_open()) {
            return Result<void, Error>::failure(
                Error(ErrorCode::IoError, "Failed to open file for writing: " + path.string())
            );
        }
        return export_to_stream(file, analysis, suggestions, options, progress);
    }

    Result<void, Error> HtmlExporter::export_to_stream(
        std::ostream& stream,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        ExportProgressCallback /* progress */
    ) const {
        using namespace bha::resources;

        // Generate embedded JSON data for JavaScript
        ExportOptions json_opts = options;
        json_opts.pretty_print = false;
        json_opts.include_suggestions = false;

        JsonExporter json_exporter;
        auto json_result = json_exporter.export_to_string(analysis, suggestions, json_opts);
        if (json_result.is_err()) {
            return Result<void, Error>::failure(json_result.error());
        }

        std::string theme_class = options.html_dark_mode ? "dark-theme" : "light-theme";
        std::string timestamp = format_timestamp(std::chrono::system_clock::now());

        // ==================================================================
        // 1. Build HTML HEAD section
        // ==================================================================
        std::string head = replace_placeholders(REPORT_HEAD_HTML, {
            {"{{TITLE}}", escape_html(options.html_title)},
            {"{{FONTAWESOME_CSS}}", std::string(FONTAWESOME_CSS_DATA)},
            {"{{STYLES_CSS}}", std::string(STYLES_CSS)}
        });

        // ==================================================================
        // 2. Build BODY START section (header + summary cards)
        // ==================================================================
        std::ostringstream summary_stats;
        summary_stats << std::fixed << std::setprecision(1);
        summary_stats << (duration_to_ms(analysis.performance.total_build_time) / 1000.0);
        std::string total_build_time_str = summary_stats.str();

        summary_stats.str("");
        summary_stats << std::fixed << std::setprecision(1);
        summary_stats << duration_to_ms(analysis.performance.avg_file_time);
        std::string avg_file_time_str = summary_stats.str();

        summary_stats.str("");
        summary_stats.clear();
        summary_stats << std::fixed << std::setprecision(1);
        summary_stats << analysis.cache_distribution.cache_hit_opportunity_percent;
        std::string cache_hit_opportunity_str = summary_stats.str();

        summary_stats.str("");
        summary_stats.clear();
        summary_stats << std::fixed << std::setprecision(1);
        summary_stats << analysis.cache_distribution.distributed_suitability_score;
        std::string distributed_suitability_str = summary_stats.str();

        std::string body_start = replace_placeholders(REPORT_BODY_START_HTML, {
            {"{{THEME_CLASS}}", theme_class},
            {"{{TITLE}}", escape_html(options.html_title)},
            {"{{TIMESTAMP}}", timestamp},
            {"{{TOTAL_FILES}}", std::to_string(analysis.files.size())},
            {"{{TOTAL_BUILD_TIME}}", total_build_time_str},
            {"{{AVG_FILE_TIME}}", avg_file_time_str},
            {"{{CACHE_HIT_OPPORTUNITY}}", cache_hit_opportunity_str},
            {"{{CACHE_RISK_UNITS}}", std::to_string(analysis.cache_distribution.cache_risk_compilations)},
            {"{{DISTRIBUTED_SUITABILITY}}", distributed_suitability_str}
        });

        // ==================================================================
        // 3. Build FILE TABLE ROWS (dynamic content)
        // ==================================================================
        std::ostringstream file_rows;
        auto sorted_files = analysis.files;
        std::ranges::sort(sorted_files,
                          [](const auto& a, const auto& b) { return a.compile_time > b.compile_time; });

        Duration max_time = sorted_files.empty() ? Duration::zero() : sorted_files[0].compile_time;

        auto format_bytes = [](size_t bytes) -> std::string {
            if (bytes == 0) return "-";
            if (bytes < 1024) return std::to_string(bytes) + " B";
            if (bytes < 1024 * 1024) return std::to_string(bytes / 1024) + " KB";
            return std::to_string(bytes / (1024 * 1024)) + " MB";
        };

        for (const auto& file : sorted_files) {
            double time_ms = duration_to_ms(file.compile_time);
            double fe_ms = duration_to_ms(file.frontend_time);
            double be_ms = duration_to_ms(file.backend_time);
            double bar_width = max_time.count() > 0
                ? 100.0 * static_cast<double>(file.compile_time.count()) / static_cast<double>(max_time.count())
                : 0.0;

            std::string stack_usage = format_bytes(file.memory.max_stack_bytes);

            file_rows << "\n                            <tr data-time=\"" << time_ms << "\" data-name=\""
                      << escape_html(file.file.string()) << "\">\n"
                      << R"(                                <td><i class="fas fa-file-code" style="color: var(--accent-color); margin-right: 8px;"></i>)"
                      << escape_html(file.file.string()) << "</td>\n"
                      << "                                <td><strong>" << std::fixed << std::setprecision(1) << time_ms << " ms</strong></td>\n"
                      << "                                <td>" << std::fixed << std::setprecision(1) << fe_ms << " ms</td>\n"
                      << "                                <td>" << std::fixed << std::setprecision(1) << be_ms << " ms</td>\n"
                      << "                                <td>" << stack_usage << "</td>\n"
                      << "                                <td>\n"
                      << "                                    <div class=\"time-bar-container\">\n"
                      << R"(                                        <div class="time-bar" style="width: )" << bar_width << "%\"></div>\n"
                      << "                                    </div>\n"
                      << "                                </td>\n"
                      << "                            </tr>";
        }

        // ==================================================================
        // 4. Build SUGGESTION CARDS (dynamic content)
        // ==================================================================
        std::ostringstream suggestion_cards;
        auto priority_rank = [](const Priority priority) {
            switch (priority) {
                case Priority::Critical: return 4;
                case Priority::High: return 3;
                case Priority::Medium: return 2;
                case Priority::Low: return 1;
            }
            return 0;
        };

        std::size_t critical_count = 0;
        std::size_t high_count = 0;
        std::size_t medium_count = 0;
        std::size_t low_count = 0;
        Duration total_savings = Duration::zero();

        std::vector<std::size_t> suggestion_order(suggestions.size());
        std::iota(suggestion_order.begin(), suggestion_order.end(), 0);
        std::ranges::sort(suggestion_order, [&](const std::size_t lhs, const std::size_t rhs) {
            const auto& a = suggestions[lhs];
            const auto& b = suggestions[rhs];
            const int a_rank = priority_rank(a.priority);
            const int b_rank = priority_rank(b.priority);
            if (a_rank != b_rank) {
                return a_rank > b_rank;
            }
            if (a.estimated_savings != b.estimated_savings) {
                return a.estimated_savings > b.estimated_savings;
            }
            return a.confidence > b.confidence;
        });

        for (const auto& suggestion : suggestions) {
            total_savings += suggestion.estimated_savings;
            switch (suggestion.priority) {
                case Priority::Critical: ++critical_count; break;
                case Priority::High: ++high_count; break;
                case Priority::Medium: ++medium_count; break;
                case Priority::Low: ++low_count; break;
            }
        }

        const std::size_t quick_pick_count = std::min<std::size_t>(3, suggestion_order.size());
        suggestion_cards << "<div class=\"suggestions-overview\">\n"
                        << "  <div class=\"dep-stats\">\n"
                        << "    <div class=\"dep-stat\"><div class=\"dep-stat-value\">" << suggestions.size() << "</div><div class=\"dep-stat-label\">Total Suggestions</div></div>\n"
                        << "    <div class=\"dep-stat\"><div class=\"dep-stat-value\">" << (critical_count + high_count) << "</div><div class=\"dep-stat-label\">High Impact</div></div>\n"
                        << "    <div class=\"dep-stat\"><div class=\"dep-stat-value\">" << format_duration_human(total_savings) << "</div><div class=\"dep-stat-label\">Est. Total Savings</div></div>\n"
                        << "    <div class=\"dep-stat\"><div class=\"dep-stat-value\">" << critical_count << "/" << high_count << "/" << medium_count << "/" << low_count
                        << "</div><div class=\"dep-stat-label\">C/H/M/L Mix</div></div>\n"
                        << "  </div>\n"
                        << "  <p class=\"suggestions-guidance\">Suggestions are optimization hypotheses. Validate with rebuild + tests before rollout.</p>\n";

        if (quick_pick_count > 0) {
            suggestion_cards << "  <h3 class=\"suggestions-subtitle\"><i class=\"fas fa-bolt\"></i> Top Actions</h3>\n"
                            << "  <div class=\"suggestion-quick-list\">\n";

            for (std::size_t i = 0; i < quick_pick_count; ++i) {
                const std::size_t idx = suggestion_order[i];
                const auto& suggestion = suggestions[idx];
                suggestion_cards << "    <a class=\"suggestion-quick-item\" href=\"#suggestion-" << idx << "\">\n"
                                << "      <span class=\"suggestion-quick-title\">" << escape_html(suggestion.title) << "</span>\n"
                                << "      <span class=\"suggestion-quick-meta\">" << escape_html(to_string(suggestion.type))
                                << " · " << format_duration_human(suggestion.estimated_savings) << "</span>\n"
                                << "    </a>\n";
            }

            suggestion_cards << "  </div>\n";
        }

        suggestion_cards << "</div>\n";

        if (!suggestions.empty()) {
            suggestion_cards << "<details class=\"suggestions-full-list\">\n"
                            << "  <summary class=\"suggestions-full-summary\"><i class=\"fas fa-list\"></i> View Full Suggestion Details (" << suggestions.size() << ")</summary>\n"
                            << "  <div class=\"suggestions-full-list-body\">\n";
        } else {
            suggestion_cards << "<div class=\"info-badge\"><i class=\"fas fa-info-circle\"></i> No suggestions generated for this run.</div>\n";
        }

        for (const auto suggestion_index : suggestion_order) {
            const auto& sugg = suggestions[suggestion_index];
            std::string badge_class = "badge-low";
            std::string priority_text = "Low";
            if (sugg.priority == Priority::Critical) {
                badge_class = "badge-critical";
                priority_text = "Critical";
            } else if (sugg.priority == Priority::High) {
                badge_class = "badge-high";
                priority_text = "High";
            } else if (sugg.priority == Priority::Medium) {
                badge_class = "badge-medium";
                priority_text = "Medium";
            }

            const std::string type_text = to_string(sugg.type);
            const std::string target_path = sugg.target_file.path.empty()
                ? "Unknown"
                : escape_html(sugg.target_file.path.string());
            const std::string savings_human = format_duration_human(sugg.estimated_savings);
            const bool has_steps = !sugg.implementation_steps.empty();
            const bool has_caveats = !sugg.caveats.empty();
            const bool has_rationale = !sugg.rationale.empty();
            const bool has_verification = !sugg.verification.empty();
            const bool has_docs = sugg.documentation_link.has_value() && !sugg.documentation_link->empty();
            const bool has_hotspot_origins = !sugg.hotspot_origins.empty();
            const bool has_blocked_reason =
                sugg.auto_apply_blocked_reason.has_value() && !sugg.auto_apply_blocked_reason->empty();

            suggestion_cards << "\n                <div class=\"suggestion-card\" id=\"suggestion-" << suggestion_index << "\">\n"
                            << "                    <div class=\"suggestion-header\">\n"
                            << "                        <div class=\"suggestion-title-block\">\n"
                            << "                            <span class=\"suggestion-title\">" << escape_html(sugg.title) << "</span>\n"
                            << "                            <div class=\"suggestion-chips\">\n"
                            << "                                <span class=\"chip chip-type\"><i class=\"fas fa-tag\"></i> " << escape_html(type_text) << "</span>\n"
                            << "                                <span class=\"chip " << badge_class << "\">" << priority_text << "</span>\n";

            if (sugg.is_safe) {
                suggestion_cards << "                                <span class=\"chip chip-safe\"><i class=\"fas fa-shield-check\"></i> Safe</span>\n";
            }

            suggestion_cards << "                            </div>\n"
                            << "                        </div>\n"
                            << "                    </div>\n"
                            << "                    <div class=\"suggestion-meta-grid\">\n"
                            << "                        <div class=\"meta-pill\">\n"
                            << "                            <i class=\"fas fa-map-marker-alt\"></i>\n"
                            << "                            <div>\n"
                            << "                                <div class=\"meta-label\">Target</div>\n"
                            << "                                <div class=\"meta-value\">" << target_path;

            if (sugg.target_file.line_start > 0) {
                suggestion_cards << ":" << sugg.target_file.line_start;
            }

            suggestion_cards << "</div>\n"
                            << "                            </div>\n"
                            << "                        </div>\n"
                            << "                        <div class=\"meta-pill\">\n"
                            << "                            <i class=\"fas fa-percentage\"></i>\n"
                            << "                            <div>\n"
                            << "                                <div class=\"meta-label\">Confidence</div>\n"
                            << "                                <div class=\"meta-value\">" << std::fixed << std::setprecision(0) << (sugg.confidence * 100) << "%</div>\n"
                            << "                            </div>\n"
                            << "                        </div>\n"
                            << "                        <div class=\"meta-pill\">\n"
                            << "                            <i class=\"fas fa-clock\"></i>\n"
                            << "                            <div>\n"
                            << "                                <div class=\"meta-label\">Est. Savings</div>\n"
                            << "                                <div class=\"meta-value\">" << savings_human << "</div>\n"
                            << "                            </div>\n"
                            << "                        </div>\n"
                            << "                        <div class=\"meta-pill\">\n"
                            << "                            <i class=\"fas fa-layer-group\"></i>\n"
                            << "                            <div>\n"
                            << "                                <div class=\"meta-label\">Edits</div>\n"
                            << "                                <div class=\"meta-value\">" << sugg.edits.size() << "</div>\n"
                            << "                            </div>\n"
                            << "                        </div>\n"
                            << "                        <div class=\"meta-pill\">\n"
                            << "                            <i class=\"fas fa-wand-magic-sparkles\"></i>\n"
                            << "                            <div>\n"
                            << "                                <div class=\"meta-label\">Apply</div>\n"
                            << "                                <div class=\"meta-value\">" << escape_html(application_mode_label(sugg)) << "</div>\n"
                            << "                            </div>\n"
                            << "                        </div>\n"
                            << "                    </div>\n"
                            << "                    <div class=\"suggestion-section\">\n"
                            << "                        <h4><i class=\"fas fa-lightbulb\"></i> What & Why</h4>\n"
                            << "                        <div class=\"suggestion-description\">" << format_markdown_simple(sugg.description) << "</div>\n";

            if (has_rationale) {
                suggestion_cards << "                        <div class=\"suggestion-rationale\">" << format_markdown_simple(sugg.rationale) << "</div>\n";
            }

            suggestion_cards << "                    </div>\n";

            if (has_steps) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-list-check\"></i> How to Apply</h4>\n"
                                << "                        <p style=\"margin: 0 0 10px 0; color: var(--text-secondary);\">"
                                << escape_html(application_mode_note(sugg)) << "</p>\n"
                                << "                        <ol class=\"suggestion-steps\">\n";
                for (const auto& step : sugg.implementation_steps) {
                    suggestion_cards << "                            <li>" << escape_html(step) << "</li>\n";
                }
                suggestion_cards << "                        </ol>\n"
                                << "                    </div>\n";
            } else {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-list-check\"></i> How to Apply</h4>\n"
                                << "                        <p style=\"margin: 0; color: var(--text-secondary);\">"
                                << escape_html(application_mode_note(sugg)) << "</p>\n"
                                << "                    </div>\n";
            }

            if (has_blocked_reason) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-lock\"></i> Why Manual Review</h4>\n"
                                << "                        <p style=\"margin: 0; color: var(--warning-color); font-weight: 500;\">"
                                << escape_html(*sugg.auto_apply_blocked_reason) << "</p>\n"
                                << "                    </div>\n";
            }

            if (sugg.refactor_class_name || sugg.refactor_compile_commands_path) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-diagram-project\"></i> Refactor Context</h4>\n";
                if (sugg.refactor_class_name) {
                    suggestion_cards << "                        <div class=\"target-file\">Class: "
                                    << escape_html(*sugg.refactor_class_name) << "</div>\n";
                }
                if (sugg.refactor_compile_commands_path) {
                    suggestion_cards << "                        <div class=\"target-file\">Compile DB: "
                                    << escape_html(sugg.refactor_compile_commands_path->string()) << "</div>\n";
                }
                suggestion_cards << "                    </div>\n";
            }

            if (has_verification) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-clipboard-check\"></i> Verify</h4>\n"
                                << "                        <div class=\"suggestion-description\">" << format_markdown_simple(sugg.verification) << "</div>\n"
                                << "                    </div>\n";
            }

            if (has_hotspot_origins) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-route\"></i> Hotspot Origin</h4>\n";

                for (const auto& origin : sugg.hotspot_origins) {
                    suggestion_cards << "                        <div class=\"meta-pill\" style=\"margin-bottom: 10px;\">\n"
                                    << "                            <i class=\"fas fa-link\"></i>\n"
                                    << "                            <div>\n"
                                    << "                                <div class=\"meta-label\">" << escape_html(origin.kind) << "</div>\n"
                                    << "                                <div class=\"meta-value\">";
                    if (origin.estimated_cost > Duration::zero()) {
                        suggestion_cards << format_duration_human(origin.estimated_cost) << " · ";
                    }
                    suggestion_cards << escape_html(origin.note.empty()
                        ? std::string("Origin evidence from build trace")
                        : origin.note) << "</div>\n"
                                    << "                            </div>\n"
                                    << "                        </div>\n";

                    if (!origin.chain.empty()) {
                        suggestion_cards << "                        <pre class=\"code-block\" style=\"margin-top: 0;\">";
                        for (std::size_t chain_idx = 0; chain_idx < origin.chain.size(); ++chain_idx) {
                            if (chain_idx > 0) {
                                suggestion_cards << "\n-> ";
                            }
                            suggestion_cards << escape_html(origin.chain[chain_idx]);
                        }
                        suggestion_cards << "</pre>\n";
                    }
                }

                suggestion_cards << "                    </div>\n";
            }

            if (has_caveats) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-triangle-exclamation\"></i> Risks & Caveats</h4>\n"
                                << "                        <ul class=\"suggestion-caveats\">\n";
                for (const auto& caveat : sugg.caveats) {
                    suggestion_cards << "                            <li>" << escape_html(caveat) << "</li>\n";
                }
                suggestion_cards << "                        </ul>\n"
                                << "                    </div>\n";
            }

            if (has_docs) {
                suggestion_cards << "                    <div class=\"suggestion-section\">\n"
                                << "                        <h4><i class=\"fas fa-book\"></i> Documentation</h4>\n"
                                << "                        <a class=\"suggestion-link\" href=\"" << escape_html(*sugg.documentation_link)
                                << "\" target=\"_blank\" rel=\"noopener noreferrer\">" << escape_html(*sugg.documentation_link) << "</a>\n"
                                << "                    </div>\n";
            }

            if (!sugg.before_code.code.empty() || !sugg.after_code.code.empty()) {
                suggestion_cards << "\n                    <div class=\"code-comparison\">";

                if (!sugg.before_code.code.empty()) {
                    std::string before_file_label = !sugg.before_code.file.empty()
                        ? escape_html(sugg.before_code.file.string())
                        : "Current Code";

                    suggestion_cards << "\n                        <div style=\"min-width: 0; display: flex; flex-direction: column;\">\n"
                                    << "                            <div style=\"font-size: 0.9rem; color: var(--text-primary); margin-bottom: 10px; font-weight: 700; display: flex; align-items: center; gap: 8px;\">\n"
                                    << "                                <i class=\"fas fa-times-circle\" style=\"color: var(--danger-color); font-size: 1.1rem;\"></i>\n"
                                    << "                                <span style=\"background: linear-gradient(135deg, var(--danger-color), #c82333); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\">Before</span>\n"
                                    << "                            </div>\n"
                                    << "                            <div style=\"font-size: 0.75rem; color: var(--text-secondary); margin-bottom: 8px; font-style: italic;\">\n"
                                    << "                                <i class=\"fas fa-file-code\"></i> " << before_file_label << "\n"
                                    << "                            </div>\n"
                                    << R"(                            <pre class="code-block" style="flex: 1; margin: 0;">)" << escape_html(sugg.before_code.code) << "</pre>\n"
                                    << "                        </div>";
                } else {
                    suggestion_cards << "\n                        <div></div>";
                }

                if (!sugg.after_code.code.empty()) {
                    std::string after_file_label = !sugg.after_code.file.empty()
                        ? escape_html(sugg.after_code.file.string())
                        : "Optimized Code";

                    suggestion_cards << "\n                        <div style=\"min-width: 0; display: flex; flex-direction: column;\">\n"
                                    << "                            <div style=\"font-size: 0.9rem; color: var(--text-primary); margin-bottom: 10px; font-weight: 700; display: flex; align-items: center; gap: 8px;\">\n"
                                    << "                                <i class=\"fas fa-check-circle\" style=\"color: var(--success-color); font-size: 1.1rem;\"></i>\n"
                                    << "                                <span style=\"background: linear-gradient(135deg, var(--success-color), #28a745); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text;\">After</span>\n"
                                    << "                            </div>\n"
                                    << "                            <div style=\"font-size: 0.75rem; color: var(--text-secondary); margin-bottom: 8px; font-style: italic;\">\n"
                                    << "                                <i class=\"fas fa-file-code\"></i> " << after_file_label << "\n"
                                    << "                            </div>\n"
                                    << R"(                            <pre class="code-block" style="flex: 1; margin: 0; border-left: 3px solid var(--success-color);">)" << escape_html(sugg.after_code.code) << "</pre>\n"
                                    << "                        </div>";
                }

                suggestion_cards << "\n                    </div>";
            }

            if (!sugg.edits.empty()) {
                std::map<std::string, std::vector<TextEdit>> edits_by_file;
                for (const auto& edit : sugg.edits) {
                    edits_by_file[edit.file.string()].push_back(edit);
                }

                suggestion_cards << "\n                    <details class=\"suggestion-edits\">\n"
                                << "                        <summary class=\"suggestion-edits-summary\">\n"
                                << "                            <span><i class=\"fas fa-code\"></i> Text Edits</span>\n"
                                << "                            <span class=\"edit-summary\">" << sugg.edits.size() << " changes</span>\n"
                                << "                        </summary>\n"
                                << "                        <div class=\"suggestion-edits-body\">\n";

                for (const auto& [file_path, file_edits] : edits_by_file) {
                    suggestion_cards << "                            <div class=\"edit-file-group\">\n"
                                    << "                                <div class=\"edit-file-header\">\n"
                                    << "                                    <i class=\"fas fa-file-code\"></i>\n"
                                    << "                                    <span class=\"edit-file-name\">" << escape_html(file_path) << "</span>\n"
                                    << "                                    <span class=\"edit-file-count\">" << file_edits.size() << " edits</span>\n"
                                    << "                                </div>\n";

                    for (std::size_t edit_idx = 0; edit_idx < file_edits.size(); ++edit_idx) {
                        const auto& edit = file_edits[edit_idx];
                        suggestion_cards << "                                <div class=\"text-edit\">\n"
                                        << "                                    <div class=\"text-edit-meta\">\n"
                                        << "                                        <span class=\"edit-range\">[" << edit.start_line << ":" << edit.start_col
                                        << " → " << edit.end_line << ":" << edit.end_col << "]</span>\n"
                                        << "                                    </div>\n";

                        if (!edit.new_text.empty()) {
                            const std::size_t total_lines = count_lines(edit.new_text);
                            const bool is_large = edit.new_text.size() > 8000 || total_lines > 200;
                            const std::string preview_text = is_large
                                ? truncate_lines(edit.new_text, 80)
                                : edit.new_text;

                            suggestion_cards << R"(                                    <pre class="code-block code-edit-block">)"
                                            << escape_html(preview_text) << "</pre>\n";

                            if (is_large) {
                                suggestion_cards << "                                    <details class=\"edit-expand\">\n"
                                                << "                                        <summary>Show full edit</summary>\n"
                                                << R"(                                        <pre class="code-block code-edit-block">)"
                                                << escape_html(edit.new_text) << "</pre>\n"
                                                << "                                    </details>\n";
                            }
                        } else {
                            suggestion_cards << "                                    <div class=\"edit-delete\">\n"
                                            << "                                        <i class=\"fas fa-trash-alt\"></i> Delete this range\n"
                                            << "                                    </div>\n";
                        }

                        suggestion_cards << "                                </div>\n";
                    }

                    suggestion_cards << "                            </div>\n";
                }

                suggestion_cards << "                        </div>\n"
                                << "                    </details>";
            }

            suggestion_cards << "\n                </div>";
        }

        if (!suggestions.empty()) {
            suggestion_cards << "  </div>\n"
                            << "</details>\n";
        }

        // ==================================================================
        // 5. Build BODY SECTIONS with placeholders filled
        // ==================================================================
        std::string circular_deps_color = analysis.dependencies.circular_dependencies.empty()
            ? "var(--success-color)"
            : "var(--danger-color)";

        std::string body_sections = replace_placeholders(REPORT_BODY_SECTIONS_HTML, {
            {"{{FILE_TABLE_ROWS}}", file_rows.str()},
            {"{{SUGGESTION_CARDS}}", suggestion_cards.str()},
            {"{{TOTAL_INCLUDES}}", std::to_string(analysis.dependencies.total_includes)},
            {"{{UNIQUE_HEADERS}}", std::to_string(analysis.dependencies.unique_headers)},
            {"{{MAX_INCLUDE_DEPTH}}", std::to_string(analysis.dependencies.max_include_depth)},
            {"{{CIRCULAR_DEPS_COLOR}}", circular_deps_color},
            {"{{CIRCULAR_DEPS_COUNT}}", std::to_string(analysis.dependencies.circular_dependencies.size())}
        });

        // ==================================================================
        // 6. Build BODY END section (D3.js + visualization script)
        // ==================================================================
        std::string body_end = replace_placeholders(REPORT_BODY_END_HTML, {
            {"{{D3_JS}}", std::string(D3_JS_DATA)},
            {"{{ANALYSIS_JSON}}", json_result.value()},
            {"{{VISUALIZATION_JS}}", std::string(VISUALIZATION_JS)}
        });

        // ==================================================================
        // 7. Stream all sections to output
        // ==================================================================
        stream << head
               << body_start
               << body_sections
               << body_end;

        return Result<void, Error>::success();
    }

    Result<std::string, Error> HtmlExporter::export_to_string(
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options
    ) const {
        std::ostringstream ss;
        if (auto result = export_to_stream(ss, analysis, suggestions, options, nullptr); result.is_err()) {
            return Result<std::string, Error>::failure(result.error());
        }
        return Result<std::string, Error>::success(ss.str());
    }

    // =============================================================================
    // CSV Exporter
    // =============================================================================

    Result<void, Error> CsvExporter::export_to_file(
        const fs::path& path,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        const ExportProgressCallback progress
    ) const {
        std::ofstream file(path);
        if (!file.is_open()) {
            return Result<void, Error>::failure(
                Error(ErrorCode::IoError, "Failed to open file for writing: " + path.string())
            );
        }
        return export_to_stream(file, analysis, suggestions, options, progress);
    }

    Result<void, Error> CsvExporter::export_to_stream(
        std::ostream& stream,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        ExportProgressCallback
    ) const {
        stream << "# Files\n";
        stream << "Path,Total Time (ms),Frontend Time (ms),Backend Time (ms),Include Count\n";

        for (const auto& file : analysis.files) {
            if (options.min_compile_time > Duration::zero() &&
                file.compile_time < options.min_compile_time) {
                continue;
                }

            stream << escape_csv(file.file.string()) << ","
                   << std::fixed << std::setprecision(3) << duration_to_ms(file.compile_time) << ","
                   << duration_to_ms(file.frontend_time) << ","
                   << duration_to_ms(file.backend_time) << ","
                   << file.include_count << "\n";
        }

        if (options.include_suggestions && !suggestions.empty()) {
            stream << "\n# Suggestions\n";
            stream << "Type,Title,Target File,Line,Confidence,Priority,Estimated Savings (ms),Edits Count,Is Safe,Application Mode,Application Summary,Auto-Apply Blocked Reason\n";

            for (const auto& sugg : suggestions) {
                if (sugg.confidence < options.min_confidence) {
                    continue;
                }

                stream << static_cast<int>(sugg.type) << ","
                       << escape_csv(sugg.title) << ","
                       << escape_csv(sugg.target_file.path.string()) << ","
                       << sugg.target_file.line_start << ","
                       << std::fixed << std::setprecision(2) << sugg.confidence << ","
                       << static_cast<int>(sugg.priority) << ","
                       << duration_to_ms(sugg.estimated_savings) << ","
                       << sugg.edits.size() << ","
                       << (sugg.is_safe ? "true" : "false") << ","
                       << escape_csv(to_string(resolve_application_mode(sugg))) << ","
                       << escape_csv(sugg.application_summary.value_or("")) << ","
                       << escape_csv(sugg.auto_apply_blocked_reason.value_or("")) << "\n";
            }
        }

        return Result<void, Error>::success();
    }

    Result<std::string, Error> CsvExporter::export_to_string(
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options
    ) const {
        std::ostringstream ss;
        if (auto result = export_to_stream(ss, analysis, suggestions, options, nullptr); result.is_err()) {
            return Result<std::string, Error>::failure(result.error());
        }
        return Result<std::string, Error>::success(ss.str());
    }

    // =============================================================================
    // Markdown Exporter
    // =============================================================================

    Result<void, Error> MarkdownExporter::export_to_file(
        const fs::path& path,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        const ExportProgressCallback progress
    ) const {
        std::ofstream file(path);
        if (!file.is_open()) {
            return Result<void, Error>::failure(
                Error(ErrorCode::IoError, "Failed to open file for writing: " + path.string())
            );
        }
        return export_to_stream(file, analysis, suggestions, options, progress);
    }

    Result<void, Error> MarkdownExporter::export_to_stream(
        std::ostream& stream,
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options,
        ExportProgressCallback
    ) const {
        stream << "# Build Hotspot Analysis Report\n\n";
        stream << "_Generated by BHA v2.0 on " << format_timestamp(std::chrono::system_clock::now()) << "_\n\n";

        stream << "## Summary\n\n";
        stream << "| Metric | Value |\n";
        stream << "|--------|-------|\n";
        stream << "| Total Files | " << analysis.files.size() << " |\n";
        stream << "| Total Build Time | " << std::fixed << std::setprecision(2)
               << duration_to_ms(analysis.performance.total_build_time) / 1000.0 << " s |\n";
        stream << "| Avg File Time | " << duration_to_ms(analysis.performance.avg_file_time) << " ms |\n";
        stream << "| Parallelism Efficiency | " << std::setprecision(1) << (analysis.performance.parallelism_efficiency * 100.0) << "% |\n";
        stream << "| Cache Hit Opportunity | " << std::setprecision(1) << analysis.cache_distribution.cache_hit_opportunity_percent << "% |\n";
        stream << "| Cache Risk Compilations | " << analysis.cache_distribution.cache_risk_compilations << " |\n";
        stream << "| Distributed Suitability | " << std::setprecision(1) << analysis.cache_distribution.distributed_suitability_score << "% |\n";
        stream << "| Suggestions | " << suggestions.size() << " |\n\n";

        if (options.include_file_details) {
            stream << "## Top Files by Compile Time\n\n";
            stream << "| File | Time (ms) | Frontend | Backend |\n";
            stream << "|------|-----------|----------|---------|\n";

            auto sorted_files = analysis.files;
            std::ranges::sort(sorted_files,
                              [](const auto& a, const auto& b) { return a.compile_time > b.compile_time; });

            std::size_t count = 0;
            for (const auto& file : sorted_files) {
                if (options.max_files > 0 && count >= options.max_files) break;
                if (count >= 20) break;  // Default limit for Markdown

                stream << "| " << file.file.filename().string()
                       << " | " << std::fixed << std::setprecision(1) << duration_to_ms(file.compile_time)
                       << " | " << duration_to_ms(file.frontend_time)
                       << " | " << duration_to_ms(file.backend_time) << " |\n";
                count++;
            }
            stream << "\n";
        }

        if (options.include_suggestions && !suggestions.empty()) {
            stream << "## Optimization Suggestions\n\n";

            for (const auto& sugg : suggestions) {
                if (sugg.confidence < options.min_confidence) continue;

                std::string priority;
                switch (sugg.priority) {
                case Priority::Critical: priority = "CRITICAL"; break;
                case Priority::High: priority = "HIGH"; break;
                case Priority::Medium: priority = "MEDIUM"; break;
                case Priority::Low: priority = "LOW"; break;
                }

                stream << "### " << sugg.title << "\n\n";
                stream << "**Priority:** " << priority
                       << " | **Confidence:** " << std::fixed << std::setprecision(0)
                       << (sugg.confidence * 100) << "%"
                       << " | **Est. Savings:** " << format_duration_human(sugg.estimated_savings) << "\n\n";
                stream << "**File:** `" << sugg.target_file.path.string() << ":" << sugg.target_file.line_start << "`\n\n";
                stream << sugg.description << "\n\n";

                if (!sugg.before_code.code.empty()) {
                    stream << "**Before:**\n```cpp\n" << sugg.before_code.code << "\n```\n\n";
                }
                if (!sugg.after_code.code.empty()) {
                    stream << "**After:**\n```cpp\n" << sugg.after_code.code << "\n```\n\n";
                }

                if (!sugg.edits.empty()) {
                    stream << "<details>\n<summary><strong>Text Edits (" << sugg.edits.size() << ")</strong></summary>\n\n";
                    for (std::size_t edit_idx = 0; edit_idx < sugg.edits.size(); ++edit_idx) {
                        const auto& edit = sugg.edits[edit_idx];
                        stream << "**" << (edit_idx + 1) << ".** `" << edit.file.string()
                               << "` [" << edit.start_line << ":" << edit.start_col
                               << " -> " << edit.end_line << ":" << edit.end_col << "]\n\n";
                        if (!edit.new_text.empty()) {
                            stream << "```cpp\n" << edit.new_text << "\n```\n\n";
                        } else {
                            stream << "_Delete this range_\n\n";
                        }
                    }
                    stream << "</details>\n\n";
                }

                if (!sugg.hotspot_origins.empty()) {
                    stream << "**Hotspot Origin**\n\n";
                    for (const auto& origin : sugg.hotspot_origins) {
                        stream << "- **" << origin.kind << "**";
                        if (origin.estimated_cost > Duration::zero()) {
                            stream << " (" << format_duration_human(origin.estimated_cost) << ")";
                        }
                        if (!origin.note.empty()) {
                            stream << ": " << origin.note;
                        }
                        stream << "\n";
                        if (!origin.chain.empty()) {
                            stream << "  - Chain: ";
                            for (std::size_t origin_idx = 0; origin_idx < origin.chain.size(); ++origin_idx) {
                                if (origin_idx > 0) {
                                    stream << " -> ";
                                }
                                stream << "`" << origin.chain[origin_idx] << "`";
                            }
                            stream << "\n";
                        }
                    }
                    stream << "\n";
                }

                if (sugg.is_safe) {
                    stream << "> [OK] Safe to apply automatically\n\n";
                }

                stream << "---\n\n";
            }
        }

        if (options.include_dependencies) {
            stream << "## Dependency Analysis\n\n";
            stream << "- **Total Includes:** " << analysis.dependencies.total_includes << "\n";
            stream << "- **Unique Headers:** " << analysis.dependencies.unique_headers << "\n";
            stream << "- **Max Include Depth:** " << analysis.dependencies.max_include_depth << "\n";
            stream << "- **Circular Dependencies:** " << analysis.dependencies.circular_dependencies.size() << "\n\n";
        }

        if (analysis.cache_distribution.total_compilations > 0) {
            stream << "## Cache & Distribution Awareness\n\n";
            stream << "- **sccache detected:** " << (analysis.cache_distribution.sccache_detected ? "yes" : "no") << "\n";
            stream << "- **FASTBuild detected:** " << (analysis.cache_distribution.fastbuild_detected ? "yes" : "no") << "\n";
            stream << "- **Cache wrapper detected:** " << (analysis.cache_distribution.cache_wrapper_detected ? "yes" : "no") << "\n";
            stream << "- **Dynamic macro risk units:** " << analysis.cache_distribution.dynamic_macro_risk_count << "\n";
            stream << "- **Coverage/profile risk units:** " << analysis.cache_distribution.profile_or_coverage_risk_count << "\n";
            stream << "- **PCH generation risk units:** " << analysis.cache_distribution.pch_generation_risk_count << "\n";
            stream << "- **Volatile path risk units:** " << analysis.cache_distribution.volatile_path_risk_count << "\n";
            stream << "- **Heavy translation units:** " << analysis.cache_distribution.heavy_translation_units << "\n";
            stream << "- **Largest homogeneous command group:** " << analysis.cache_distribution.homogeneous_command_units << "\n\n";
        }

        return Result<void, Error>::success();
    }

    Result<std::string, Error> MarkdownExporter::export_to_string(
        const analyzers::AnalysisResult& analysis,
        const std::vector<Suggestion>& suggestions,
        const ExportOptions& options
    ) const {
        std::ostringstream ss;
        if (auto result = export_to_stream(ss, analysis, suggestions, options, nullptr); result.is_err()) {
            return Result<std::string, Error>::failure(result.error());
        }
        return Result<std::string, Error>::success(ss.str());
    }
} // namespace bha::exporters
